plugins { id 'com.android.application' }

android {
    namespace 'io.gamedeck.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'io.gamedeck.mobile.preview'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '0.2.1-preview'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
