import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url); const {createInputProtocol,HARD_CAPS}=require('../play-session-input-protocol.js');
let passed=0;const test=(n,f)=>{f();passed++;console.log(`ok - ${n}`)};

test('connect requires authoritative snapshot and tracks ack',()=>{const p=createInputProtocol();assert.equal(p.connect({nowMs:0}).resyncRequired,true);assert.equal(p.enqueue({type:'delta',sequence:1,pressed:['A'],released:[]},{nowMs:1}).reasonCode,'snapshot_required');p.connect({nowMs:2});assert.equal(p.enqueue({type:'snapshot',sequence:1,buttons:['A']},{nowMs:3}).ok,true);assert.equal(p.processNext({nowMs:4}).highestProcessedAck,1)});
test('strict keys and circular or BigInt payloads reject safely',()=>{const p=createInputProtocol();p.connect({nowMs:0});assert.equal(p.enqueue({type:'snapshot',sequence:1,buttons:[],extra:true},{nowMs:1}).reasonCode,'invalid_message_keys');const c={type:'snapshot',sequence:1,buttons:[]};c.self=c;assert.equal(p.enqueue(c,{nowMs:2}).reasonCode,'unserializable_payload');assert.equal(p.enqueue({type:'snapshot',sequence:1,buttons:[],x:1n},{nowMs:3}).reasonCode,'unserializable_payload')});
test('security caps cannot be raised',()=>{for(const [k,v] of Object.entries(HARD_CAPS))assert.throws(()=>createInputProtocol({limits:{[k]:v+1}}),/security cap/)});
test('sequence replay and gap force safe behavior',()=>{const p=createInputProtocol();p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:[]},{nowMs:1});assert.equal(p.enqueue({type:'snapshot',sequence:1,buttons:[]},{nowMs:2}).reasonCode,'sequence_replay');const r=p.enqueue({type:'snapshot',sequence:3,buttons:[]},{nowMs:3});assert.equal(r.reasonCode,'sequence_gap');assert.equal(r.releaseAll,true)});
test('overflow compacts projected press and release without sequence discontinuity',()=>{const p=createInputProtocol({limits:{maxQueueDepth:2}});p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:[]},{nowMs:1});p.enqueue({type:'delta',sequence:2,pressed:['A'],released:[]},{nowMs:2});const r=p.enqueue({type:'delta',sequence:3,pressed:[],released:['A']},{nowMs:3});assert.equal(r.compacted,true);const processed=p.processNext({nowMs:4});assert.equal(processed.highestProcessedAck,3);assert.deepEqual(processed.buttons,[]);assert.equal(p.status().highestReceived,3)});
test('overflow preserves incoming release against queued press',()=>{const p=createInputProtocol({limits:{maxQueueDepth:1}});p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:['B']},{nowMs:1});const r=p.enqueue({type:'delta',sequence:2,pressed:[],released:['B']},{nowMs:2});assert.equal(r.compacted,true);assert.deepEqual(p.processNext({nowMs:3}).buttons,[])});
test('rate limit returns release-all and snapshot resync',()=>{const p=createInputProtocol({limits:{maxEventsPerSecond:1}});p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:['A']},{nowMs:1});const r=p.enqueue({type:'delta',sequence:2,pressed:['B'],released:[]},{nowMs:2});assert.equal(r.reasonCode,'rate_limited');assert.equal(r.releaseAll,true);assert.equal(r.resyncRequired,true);assert.equal(p.status().resyncRequired,true)});
test('watchdog releases stuck buttons at 500ms',()=>{const p=createInputProtocol();p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:['A']},{nowMs:1});p.processNext({nowMs:2});assert.equal(p.watchdog({nowMs:501}).triggered,false);const r=p.watchdog({nowMs:502});assert.equal(r.triggered,true);assert.equal(r.releaseAll,true);assert.deepEqual(p.status().buttons,[])});
test('disconnect and reconnect clear stale buttons and require snapshot',()=>{const p=createInputProtocol();p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:['A']},{nowMs:1});p.processNext({nowMs:2});assert.equal(p.disconnect({nowMs:3}).releaseAll,true);p.connect({nowMs:4});assert.deepEqual(p.status().buttons,[]);assert.equal(p.enqueue({type:'delta',sequence:1,pressed:['B'],released:[]},{nowMs:5}).reasonCode,'snapshot_required')});
test('nonnegative monotonic time is enforced',()=>{const p=createInputProtocol();assert.equal(p.connect({nowMs:-1}).reasonCode,'invalid_time');p.connect({nowMs:5});assert.equal(p.watchdog({nowMs:4}).reasonCode,'invalid_time')});
test('release-all message clears authoritative buttons',()=>{const p=createInputProtocol();p.connect({nowMs:0});p.enqueue({type:'snapshot',sequence:1,buttons:['A']},{nowMs:1});p.processNext({nowMs:2});p.enqueue({type:'release_all',sequence:2},{nowMs:3});assert.deepEqual(p.processNext({nowMs:4}).buttons,[])});
console.log(`play-session-input-protocol: ${passed} tests passed`);
