import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'src/app.js'), 'utf8');
const controller = main.slice(main.indexOf('function setEmbeddedEngineWindowMode'), main.indexOf('function registerGameDeckOpenBorProcess'));
const prepare = controller.slice(controller.indexOf('async prepare()'), controller.indexOf('async integrate'));
const captureStarted = controller.slice(controller.indexOf('captureStarted(session)'), controller.indexOf('setAspect('));
const setModeBlock = controller.slice(controller.indexOf('async setMode(mode, session)'), controller.indexOf('release(session)'));
const popout = setModeBlock.slice(setModeBlock.indexOf("if (mode === 'popout')"), setModeBlock.indexOf("if (mainWindow.isMinimized()) mainWindow.restore()"));

assert.ok(main.includes('const hasSingleInstanceLock = app.requestSingleInstanceLock();'));
assert.ok(main.includes("app.on('second-instance'"));
assert.ok(main.includes('if (hasSingleInstanceLock) app.whenReady().then'));
assert.ok(main.includes("if (hasSingleInstanceLock) app.on('activate'"));
assert.ok(main.includes("const AUTOMATION_KEEPALIVE = process.env.GAMEDECK_AUTOMATION_KEEPALIVE === '1'"));
assert.ok(main.includes('const managedEmbeddedProcesses = new Map();'));
assert.ok(main.includes('function registerManagedEmbeddedProcess(child)'));
assert.ok(main.includes('function stopManagedEmbeddedProcesses(exceptPid = 0)'));
assert.ok(main.includes('registerManagedEmbeddedProcess(spawn(spec.executable'));
assert.ok(main.includes("embeddedPlayManager.stop(playStatus.sessionId, 'GameDeck window closed.')"));
assert.ok(main.includes('stopManagedEmbeddedProcesses();'));
assert.ok(main.includes('if (AUTOMATION_MODE && AUTOMATION_KEEPALIVE)'));
assert.ok(main.includes('SetProcessDpiAwarenessContext(IntPtr value)'));
assert.ok(main.includes('SetProcessDPIAware()'));
assert.ok(main.includes("SetProcessDpiAwarenessContext([IntPtr](-4))"));
assert.ok(prepare.includes("mainWindow.setAlwaysOnTop(true, 'screen-saver')"));
assert.ok(captureStarted.indexOf('setEmbeddedEngineWindowMode(session') < captureStarted.indexOf('mainWindow.setAlwaysOnTop(false)'));
assert.ok(controller.includes("if (session?.phase === 'playing') mainWindow.setAlwaysOnTop(false)"));
assert.ok(controller.includes("else mainWindow.setAlwaysOnTop(true, 'screen-saver')"));
assert.ok(popout.indexOf('mainWindow.minimize()') < popout.indexOf("setEmbeddedEngineWindowMode(session, 'popout')"));
assert.ok(popout.includes('setTimeout(() =>'));
assert.ok(popout.includes('}, 180);'));
assert.ok(setModeBlock.indexOf('setEmbeddedEngineWindowMode(session, mode);') < setModeBlock.indexOf('mainWindow.moveTop();'));
assert.ok(app.includes('let playCaptureGeneration = 0;'));
assert.ok(app.includes('captureGeneration !== playCaptureGeneration'));
assert.ok(app.includes("fallbackPlayCaptureToPopout('The live game window stopped sharing."));
assert.ok(app.includes('await fallbackPlayCaptureToPopout(error.message'));
assert.ok(app.includes("await setPlayMode('popout')"));

console.log('play window z-order: 28 scenarios passed');
