import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const html = fs.readFileSync(path.join(root, 'src/index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src/styles.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'src/app.js'), 'utf8');
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const haptics = fs.readFileSync(path.join(root, 'src/game-haptics.js'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');

assert.match(html, /id="playAmbient"[\s\S]*id="playAmbientVideo"/);
assert.match(html, /GAMEDECK PLAY/);
assert.match(html, /id="playHapticsToggle"[\s\S]*Haptics Auto/);
assert.match(html, /class="play-brand play-title-chip"/);
assert.match(html, /class="play-title-copy"/);
assert.match(html, />GameDeck<\/span>/);
assert.match(html, />Full screen<\/span>/);
assert.match(html, />Window<\/span>/);
assert.match(html, /class="play-control-copy"[\s\S]*<small>Haptics<\/small><b>Auto<\/b>/);
assert.match(html, /class="play-control-svg"/);
assert.doesNotMatch(html, /play-footer-guide/);
assert.ok(html.indexOf('game-haptics.js') < html.indexOf('app.js'), 'Haptics helper must load before the renderer.');
assert.doesNotMatch(html.match(/<section class="play-surface[\s\S]*?<\/section>/)?.[0] || '', /RetroArch/);

assert.match(css, /\.play-surface\s*\{[\s\S]*--ambient-left:/);
assert.match(css, /\.play-surface\.mode-docked\.play-ambient-live #playAmbientVideo/);
assert.match(css, /filter: blur\(58px\) saturate\(1\.65\) brightness\(\.48\)/);
assert.match(css, /@keyframes haptic-breath/);
assert.match(css, /\.play-haptics-toggle\.reactive span/);
assert.match(css, /\.play-haptics-toggle\.enhance/);
assert.match(css, /\.play-surface \.play-header/);
assert.match(css, /\.play-surface \.play-footer/);
assert.match(css, /translateY\(calc\(-100% - 84px\)\)/);
assert.match(css, /translate\(-50%, calc\(100% \+ 38px\)\)/);
assert.match(css, /\.play-title-chip/);
assert.match(css, /grid-template-columns: repeat\(4, minmax\(88px, auto\)\)/);
assert.match(css, /overflow: hidden;[\s\S]*white-space: nowrap;[\s\S]*text-overflow: ellipsis/);
assert.match(css, /\.play-control-svg/);
assert.match(css, /#playVideo[\s\S]*border: 0;[\s\S]*filter: none/);
assert.match(css, /backface-visibility: visible/);
assert.doesNotMatch(css.slice(css.indexOf('/* Immersive GameDeck Play chrome */')), /play-footer-guide/);
assert.equal([...css].reduce((balance, char) => balance + (char === '{' ? 1 : char === '}' ? -1 : 0), 0), 0, 'CSS braces must stay balanced');
assert.ok(css.indexOf('/* Integrated GameDeck Play surface */') > css.indexOf('.launch-handoff-spinner { animation-duration: 1.5s; }\n}'), 'Play surface must not be trapped inside reduced-motion media query');

assert.match(app, /const mode = 'docked';/);
assert.doesNotMatch(app, /writePreference\('play-mode'/);
assert.match(app, /setInterval\(samplePlayAmbientFrame, 180\)/);
assert.match(app, /playAmbientColorState = Object\.create\(null\)/);
assert.match(app, /ambientVideo\.srcObject = playCaptureStream/);
assert.match(app, /window\.deck\.playSessionArmCapture\(sessionId, includeAudio\)/);
assert.match(app, /const HAPTIC_PREFERENCE_ORDER = \['auto', 'enhance', 'off'\]/);
assert.match(app, /function hideFullscreenControls\(force = false\)/);
assert.match(app, /function settlePlayChrome\(delay = 720\)/);
assert.match(app, /hideFullscreenControls\(true\)/);
const chromeHideBlock = app.slice(app.indexOf('function hideFullscreenControls'), app.indexOf('function showFullscreenControls'));
assert.match(chromeHideBlock, /play-header:focus-within, \.play-footer:focus-within/);
assert.doesNotMatch(chromeHideBlock, /:hover/);
assert.doesNotMatch(app, /addEventListener\('mouseenter'/);
assert.match(app, /active\.blur\(\)/);
assert.match(app, /surface\.classList\.add\('play-chrome-hidden'\)/);
assert.match(app, /surface\.classList\.remove\('play-chrome-hidden'\)/);
assert.match(app, /showFullscreenControls\(2200\)/);
assert.match(app, /button\.onclick = async \(\) =>/);
const playBindingBlock = app.slice(app.indexOf("$('#searchClear').onclick"), app.indexOf("$('#playClose').onclick"));
assert.ok(playBindingBlock.includes("$$('[data-play-mode]').forEach(button => {"));
assert.ok(!playBindingBlock.includes("\n$('[data-play-mode]').forEach(button => {"));
assert.match(app, /settlePlayChrome\(720\)/);
const renderPlayBlock = app.slice(app.indexOf('function renderPlaySession'), app.indexOf('function resetPlaySessionUi'));
assert.doesNotMatch(renderPlayBlock, /if \(mode !== 'fullscreen'\) resetFullscreenControls/);
assert.match(renderPlayBlock, /if \(!playing\) \{[\s\S]*resetFullscreenControls/);
assert.doesNotMatch(renderPlayBlock, /showPlayPointer\(1400\); showFullscreenControls\(1800\)/);
assert.doesNotMatch(app, /playSurface\.addEventListener\('pointerdown'/);
const escapeBlock = app.slice(app.indexOf("} else if (event.key === 'Escape')", app.indexOf('document.onkeydown')), app.indexOf('    }\n    return;', app.indexOf("} else if (event.key === 'Escape')", app.indexOf('document.onkeydown'))));
assert.match(escapeBlock, /surface\?\.classList\.contains\('play-chrome-hidden'\)/);
assert.match(escapeBlock, /hideFullscreenControls\(true\)/);
assert.doesNotMatch(escapeBlock, /setPlayMode\('docked'\)/);
const activeGamepadBlock = app.slice(app.indexOf("if (state.playSession?.active) {", app.indexOf('function handleGamepad()')), app.indexOf('if (!gamepadState.initialized', app.indexOf('function handleGamepad()')));
assert.match(activeGamepadBlock, /setInputMode\('controller'\)/);
assert.doesNotMatch(activeGamepadBlock, /showFullscreenControls/);
assert.doesNotMatch(activeGamepadBlock, /showPlayPointer/);
assert.match(app, /playFooter = playSurface\.querySelector\('\.play-footer'\)/);
assert.match(app, /surface\?\.classList\.contains\('play-chrome-hidden'\)/);
assert.match(app, /const stagePixelWidth = Math\.max\(1, Math\.round\(stageWidth \* dpr\)\)/);
assert.match(app, /const integerScale = Math\.floor\(Math\.min/);
assert.match(app, /const leftPixel = Math\.round/);
assert.match(app, /video\.style\.left = \(leftPixel \/ dpr\)/);
assert.match(app, /video\.style\.transform = 'none'/);
assert.match(app, /video\.style\.objectFit = 'fill'/);
assert.match(app, /video\.dataset\.renderMode = integerScale >= 1 \? 'integer' : 'downsample'/);
assert.match(app, /compactLabel = preference === 'enhance' \? 'Boost'/);
assert.match(main, /video_smooth = \"false\"/);
assert.match(main, /video_shader_enable = \"false\"/);
assert.match(app, /hapticPolicyForSystem\?\.\(status\?\.systemId, preference\)/);
assert.match(app, /shouldCaptureHapticAudio\(status, previousPreference\)/);
assert.match(app, /audioRequirementChanged/);
assert.match(app, /controller\.startReactive\(playCaptureStream, status\.systemId, state\.hapticPreference\)/);
assert.match(app, /controller\.startLoading\(\)/);
assert.match(app, /let playFrameReady = false/);
assert.match(app, /let playFrameReadySessionId = ''/);
assert.ok(app.includes('function markPlayFrameReady(sessionId)'));
assert.ok(app.includes('async function waitForDecodedPlayFrame(video, sessionId)'));
assert.match(app, /requestVideoFrameCallback/);
assert.ok(app.includes('await waitForDecodedPlayFrame(video, sessionId)'));
assert.match(app, /playFrameReady && playFrameReadySessionId === current.sessionId/);
assert.ok(app.includes('ensurePlayHaptics()?.primeAudio?.()'));
assert.match(haptics, /kind: 'shot'/);
assert.match(haptics, /kind: 'bass'/);
assert.match(haptics, /kind: 'explosion'/);
assert.match(haptics, /kind: 'rumble'/);
assert.ok(haptics.includes('function primeAudio()'));
assert.match(haptics, /audioContextState/);
assert.match(app, /writePreference\('haptics', state\.hapticPreference\)/);
assert.match(haptics, /const FALLBACK_SYSTEMS = new Set/);
assert.match(haptics, /const NATIVE_RUMBLE_SYSTEMS = new Set/);
assert.match(haptics, /const HAPTIC_PREFERENCES = new Set/);
assert.match(haptics, /selected === 'enhance'/);
assert.match(haptics, /const HAPTIC_PREFERENCES = new Set\(\['auto', 'enhance', 'off'\]\)/);
assert.match(haptics, /return 'adaptive';/);
assert.doesNotMatch(haptics, /return 'native';/);
assert.match(haptics, /if \(selected === 'off'\) return 'off'/);
assert.match(haptics, /getByteFrequencyData/);
assert.match(haptics, /dual-rumble/);

assert.match(main, /\| 0x00000080 \| 0x08000000/);
assert.match(main, /& ~0x00040000/);
assert.match(main, /play-session-arm-capture'[\s\S]*includeAudio = false/);
assert.match(main, /Boolean\(includeAudio && process\.platform === 'win32'\)/);
assert.match(preload, /includeAudio = false/);
assert.match(preload, /includeAudio === true/);
assert.doesNotMatch(main, /GameDeckTaskbar|TaskbarListCom|taskbarVisible/);

assert.match(css, /Reliable GameDeck Play exit target/);
assert.match(css, /\.play-surface \.play-close \{[\s\S]*width: 52px !important;[\s\S]*height: 52px !important;/);
assert.match(app, /playCloseButton\.onpointerdown/);
assert.match(app, /event\.detail !== 0/);
assert.match(main, /autosave_interval = \"10\"/);
assert.match(main, /savestate_auto_save = \"true\"/);
assert.match(main, /savestate_auto_load = \"true\"/);
assert.match(main, /requestNativeGameWindowClose\(\{ pid, timeoutMs: 3200 \}\)/);
assert.match(main, /if \(fallbackUsed\) spawnSync\('taskkill\.exe'/);
assert.match(main, /embeddedClose: lastEmbeddedCloseResult/);
assert.match(main, /exitedGracefully: closedGracefully/);

const scenarioCount = (s => (s.match(/assert\./g) || []).length)(fs.readFileSync(new URL(import.meta.url), 'utf8'));
console.log(`play surface UI: ${scenarioCount} scenarios passed`);
